"""
agents.py — Wrapper functions for all pipeline agents.
Each agent accepts structured input, sets system/user prompts, and calls
llm_call to produce structured schemas.
"""
from __future__ import annotations

import json
from typing import Optional

from client import llm_call
from schemas import (
    ResearchFindingsOutput,
    SummarizerOutput,
    PlannerOutput,
    ResearchOutput,
    AnalystOutput,
    ReportOutput,
    CompanyPlannerOutput,
    StrategyOutput,
    ReviewerOutput,
)
from tools import search_tool, go_to_market_tool
from prompts import (
    RESEARCH_PROMPT,
    SUMMARIZER_PROMPT,
    PLANNER_PROMPT,
    RESEARCH_PROMPT_D2,
    ANALYST_PROMPT,
    ANALYST_PROMPT_COMPANY,
    REPORT_PROMPT,
    COMPANY_PLANNER_PROMPT,
    COMPANY_RESEARCH_PROMPT,
    STRATEGY_PROMPT,
    REVIEWER_PROMPT,
    SINGLE_AGENT_PROMPT,
)

# ---------------------------------------------------------------------------
# Day 1 — 2-Agent Pipeline
# ---------------------------------------------------------------------------

def research_agent_d1(user_query: str) -> ResearchFindingsOutput:
    """
    Day 1 Research Agent.

    Purpose:
        Fetch core knowledge base snippets matching user query and extract facts.

    Arguments:
        user_query: The query topic to research.

    Returns:
        A ResearchFindingsOutput model containing key findings and sources.

    Raises:
        ProviderUnavailableError: If LLM call fails.
        ValidationError: If response parsing fails.
    """
    data = search_tool(user_query)
    results_str = "\n".join(f"- {r}" for r in data["results"])
    context = (
        f"User Query: {user_query}\n\n"
        f"Retrieved Snippets:\n{results_str}\n\n"
        f"Sources: {', '.join(data['sources'])}"
    )
    return llm_call(RESEARCH_PROMPT, context, ResearchFindingsOutput, temperature=0.1)


def summarizer_agent(findings: ResearchFindingsOutput) -> SummarizerOutput:
    """
    Day 1 Summarizer Agent.

    Purpose:
        Synthesize findings from the research phase into a client summary report.

    Arguments:
        findings: The findings schema from research_agent_d1.

    Returns:
        A SummarizerOutput model with paragraph summary and next steps.

    Raises:
        ProviderUnavailableError: If LLM call fails.
        ValidationError: If response parsing fails.
    """
    context = f"Research Findings:\n{findings.model_dump_json(indent=2)}"
    return llm_call(SUMMARIZER_PROMPT, context, SummarizerOutput, temperature=0.3)


# ---------------------------------------------------------------------------
# Day 2 — 4-Agent Pipeline
# ---------------------------------------------------------------------------

def planner_agent(user_query: str) -> PlannerOutput:
    """
    Day 2 Planner Agent.

    Purpose:
        Decompose a complex business query into an objective and sequential subtasks.

    Arguments:
        user_query: The user query string.

    Returns:
        A PlannerOutput plan.

    Raises:
        ProviderUnavailableError: If LLM call fails.
        ValidationError: If response parsing fails.
    """
    return llm_call(PLANNER_PROMPT, f"Business Query: {user_query}", PlannerOutput, temperature=0.1)


def research_agent_d2(planner: PlannerOutput) -> ResearchOutput:
    """
    Day 2 Research Agent.

    Purpose:
        Gather evidence based on the subtask plan generated by the planner.

    Arguments:
        planner: The planner's task structure schema.

    Returns:
        A ResearchOutput schema containing facts and evidence citations.

    Raises:
        ProviderUnavailableError: If LLM call fails.
        ValidationError: If response parsing fails.
    """
    data = search_tool(planner.objective)
    results_str = "\n".join(f"- {r}" for r in data["results"])
    context = (
        f"Objective: {planner.objective}\n\n"
        f"Subtasks:\n{json.dumps(planner.subtasks, indent=2)}\n\n"
        f"Retrieved Snippets:\n{results_str}"
    )
    return llm_call(RESEARCH_PROMPT_D2, context, ResearchOutput, temperature=0.1)


def analyst_agent(
    research: ResearchOutput,
    recalled_context: Optional[str] = None
) -> AnalystOutput:
    """
    Day 2 Analyst Agent.

    Purpose:
        Analyze evidence-backed research findings to identify risks, insights, and recommendations.

    Arguments:
        research: The research schema containing findings.
        recalled_context: Optional historical context from long-term memory.

    Returns:
        An AnalystOutput schema containing derived strategic value.

    Raises:
        ProviderUnavailableError: If LLM call fails.
        ValidationError: If response parsing fails.
    """
    context = f"Research Findings:\n{research.model_dump_json(indent=2)}"
    if recalled_context:
        context += f"\n\nHistorical Context (recalled memory):\n{recalled_context}"
    return llm_call(ANALYST_PROMPT, context, AnalystOutput, temperature=0.3)


def report_generator_agent(
    planner: PlannerOutput,
    research: ResearchOutput,
    analyst: AnalystOutput,
) -> ReportOutput:
    """
    Report Generator Agent.

    Purpose:
        Compile intermediate plan, findings, and analysis into a business-ready executive report.

    Arguments:
        planner: The planner's objective.
        research: The gathered research.
        analyst: The analyst insights and risks.

    Returns:
        A ReportOutput schema.

    Raises:
        ProviderUnavailableError: If LLM call fails.
        ValidationError: If response parsing fails.
    """
    context = (
        f"Objective: {planner.objective}\n\n"
        f"Key Findings:\n{json.dumps(research.key_findings, indent=2)}\n\n"
        f"Insights:\n{json.dumps(analyst.insights, indent=2)}\n\n"
        f"Risks:\n{json.dumps(analyst.risks, indent=2)}\n\n"
        f"Recommendations:\n{json.dumps(analyst.recommendations, indent=2)}"
    )
    return llm_call(REPORT_PROMPT, context, ReportOutput, temperature=0.3)


# ---------------------------------------------------------------------------
# Final Project — 6-Agent Company System
# ---------------------------------------------------------------------------

def company_planner_agent(user_query: str) -> CompanyPlannerOutput:
    """
    Company Chief of Staff Planner Agent.

    Purpose:
        Evaluate business request, estimate complexity, and lay out an agent execution sequence.

    Arguments:
        user_query: High-level business inquiry.

    Returns:
        A CompanyPlannerOutput workflow structure.

    Raises:
        ProviderUnavailableError: If LLM call fails.
        ValidationError: If response parsing fails.
    """
    return llm_call(
        COMPANY_PLANNER_PROMPT,
        f"Business Request: {user_query}",
        CompanyPlannerOutput,
        temperature=0.1,
    )


def research_agent_company(plan: CompanyPlannerOutput) -> ResearchOutput:
    """
    Senior Company Research Agent.

    Purpose:
        Perform comprehensive GTM research utilizing core + market intelligence data tools.

    Arguments:
        plan: The company plan layout schema.

    Returns:
        A ResearchOutput containing statistics and sources.

    Raises:
        ProviderUnavailableError: If LLM call fails.
        ValidationError: If response parsing fails.
    """
    data = go_to_market_tool(plan.objective)
    results_str = "\n".join(f"- {r}" for r in data["results"])
    context = (
        f"Business Objective: {plan.objective}\n\n"
        f"Subtasks:\n{json.dumps(plan.subtasks, indent=2)}\n\n"
        f"Market Intelligence Snippets:\n{results_str}\n\n"
        f"Sources: {', '.join(data['sources'])}"
    )
    return llm_call(COMPANY_RESEARCH_PROMPT, context, ResearchOutput, temperature=0.1)


def analyst_agent_company(
    research: ResearchOutput,
    recalled_context: Optional[str] = None,
) -> AnalystOutput:
    """
    Senior Company Business Analyst Agent.

    Purpose:
        Generate deep strategic patterns and continuity links based on research findings.

    Arguments:
        research: The research results schema.
        recalled_context: Optional memory strings.

    Returns:
        An AnalystOutput schema.

    Raises:
        ProviderUnavailableError: If LLM call fails.
        ValidationError: If response parsing fails.
    """
    context = f"Research Findings:\n{research.model_dump_json(indent=2)}"
    if recalled_context:
        context += f"\n\nHistorical Context (recalled memory):\n{recalled_context}"
    return llm_call(ANALYST_PROMPT_COMPANY, context, AnalystOutput, temperature=0.3)


def strategy_agent(analysis: AnalystOutput) -> StrategyOutput:
    """
    Senior Strategy Consultant Agent.

    Purpose:
        Formulate target segments, positioning, and prioritized recommendation timelines from analysis.

    Arguments:
        analysis: Analyst findings.

    Returns:
        A StrategyOutput blueprint.

    Raises:
        ProviderUnavailableError: If LLM call fails.
        ValidationError: If response parsing fails.
    """
    context = (
        f"Insights:\n{json.dumps(analysis.insights, indent=2)}\n\n"
        f"Risks:\n{json.dumps(analysis.risks, indent=2)}\n\n"
        f"Analyst Recommendations:\n{json.dumps(analysis.recommendations, indent=2)}"
    )
    return llm_call(STRATEGY_PROMPT, context, StrategyOutput, temperature=0.3)


def reviewer_agent(report: ReportOutput) -> ReviewerOutput:
    """
    QA Reviewer Agent.

    Purpose:
        Assess completeness, structure, and quality scores of the compiled report.

    Arguments:
        report: Final report schema draft.

    Returns:
        A ReviewerOutput validation decision.

    Raises:
        ProviderUnavailableError: If LLM call fails.
        ValidationError: If response parsing fails.
    """
    context = f"Report to Review:\n{report.model_dump_json(indent=2)}"
    return llm_call(REVIEWER_PROMPT, context, ReviewerOutput, temperature=0.1)


# ---------------------------------------------------------------------------
# Shared — Single-Agent Baseline
# ---------------------------------------------------------------------------

def single_agent(user_query: str) -> ReportOutput:
    """
    Single Agent baseline runner.

    Purpose:
        Provide a single-turn, standard comparison output without orchestration or decomposition.

    Arguments:
        user_query: The query topic.

    Returns:
        A ReportOutput schema.

    Raises:
        ProviderUnavailableError: If LLM call fails.
        ValidationError: If response parsing fails.
    """
    data = search_tool(user_query)
    results_str = "\n".join(f"- {r}" for r in data["results"])
    context = f"User Query: {user_query}\n\nSearch Results:\n{results_str}"
    return llm_call(SINGLE_AGENT_PROMPT, context, ReportOutput, temperature=0.3)
